"use client";
import {useState,useEffect,useCallback} from 'react';
import {BookOpen,Search,RefreshCw,FolderOpen,FileText,ArrowUpRight,Quote,ScanText,Upload,ChevronLeft,ChevronRight} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Select,SelectTrigger,SelectContent,SelectItem,SelectValue} from '@/components/ui/select';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
export type Evidence={id:string;title:string;page:number;snippet:string;quality:string;subject?:string};
type Doc={id:string;title:string;path:string;subject:string;scope:string;size:number;pages:number;processed:number;text_pages:number;status:string;enabled:number;error:string;year:number|null};
const labels:Record<string,string>={queued:'等待提取',indexing:'正在提取',text:'可检索',partial:'部分页待 OCR',needs_ocr:'扫描件 · 待 OCR',excluded:'未纳入当前范围',error:'需检查文件'};
async function api(path:string,body?:unknown){const r=await fetch('/api/library/'+path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:undefined);const d=await r.json() as any;if(!r.ok)throw Error(d.error||'本地资料暂时不可用');return d;}
export default function LocalLibrary({onQuote,onOCR}:{onQuote:(e:Evidence[])=>void;onOCR:(file:File,doc:Evidence)=>void}){
 const [status,setStatus]=useState<any>(null),[docs,setDocs]=useState<Doc[]>([]),[total,setTotal]=useState(0),[offset,setOffset]=useState(0),[query,setQuery]=useState(''),[subject,setSubject]=useState('全部课程'),[filter,setFilter]=useState('所有状态'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[hits,setHits]=useState<Evidence[]>([]),[searched,setSearched]=useState(false),[preview,setPreview]=useState<Doc|Evidence|null>(null),[page,setPage]=useState(1);
 const load=useCallback(async()=>{try{const [s,d]=await Promise.all([api('status'),api('documents?'+new URLSearchParams({q:query,subject:subject==='全部课程'?'':subject,status:filter==='所有状态'?'':Object.keys(labels).find(k=>labels[k]===filter)||'',offset:String(offset)}))]);setStatus(s);setDocs(d.documents);setTotal(d.total);setError('');}catch(e){setError((e as Error).message);}},[query,subject,filter,offset]);
 useEffect(()=>{const delay=setTimeout(load,250);return()=>clearTimeout(delay)},[load]);
 useEffect(()=>{const timer=setInterval(()=>{api('status').then(setStatus).catch(()=>{});},5000);return()=>clearInterval(timer)},[]);
 async function act(fn:()=>Promise<void>){setBusy(true);try{await fn();}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 function open(doc:Doc|Evidence,p=1){setPreview(doc);setPage(p)}
 async function search(){await act(async()=>{const d=await api('search?'+new URLSearchParams({q:query,subject:subject==='全部课程'?'':subject,limit:'8'}));setHits(d.results);setSearched(true)})}
 return <section className="paper library"><div className="lesson-heading"><div><span className="pill">本地资料优先 · 不上传整本教材</span><h2>早觉雨大人的知识书架</h2></div><Button variant="outline" disabled={busy} onClick={()=>act(async()=>{await api('refresh',{});await load()})}><RefreshCw size={16}/> 更新目录</Button></div><p>新文件放入项目文件夹后会自动发现；修改已有文件会更新索引。早觉雨大人，可以从一个关键词开始查找。</p>
 {error&&<div className="feedback">{error}<Button variant="ghost" onClick={load}>重新连接</Button></div>}
 {status&&<><div className="library-stats"><div><strong>{status.totals.documents||0}</strong><span>本地文件</span></div><div><strong>{status.totals.text_pages||0}</strong><span>已有文本的页 / 段</span></div><div><strong>{(status.counts.needs_ocr||0)+(status.counts.partial||0)}</strong><span>含待识别页的文件</span></div><div><strong>{status.counts.excluded||0}</strong><span>其他卷种 / 超纲</span></div></div><div className="index-progress"><span className="status-dot on"/>{status.current.file?`正在读取：${status.current.file} · 第 ${status.current.page} 页`:status.counts.queued?'等待下一份资料':'目录已同步；新文件将自动发现'}<small>已处理 {status.totals.processed||0} 页 / 段 · 全文和索引保留本机</small></div></>}
 <div className="library-search"><div className="search-box"><Search size={18}/><Input aria-label="检索本地知识库" value={query} onChange={e=>{setQuery(e.target.value);setOffset(0);setSearched(false)}} placeholder="搜索内容或文件名，例如：导数定义、虚拟内存、2025 数学二" onKeyDown={e=>{if(e.key==='Enter')search()}}/></div><Button disabled={busy||!query.trim()} onClick={search}>检索页内内容</Button></div>
 <div className="library-filters"><Select value={subject} onValueChange={s=>{setSubject(s);setOffset(0)}}><SelectTrigger aria-label="知识库课程筛选"><SelectValue/></SelectTrigger><SelectContent>{['全部课程','数学二','数据结构','计算机组成','操作系统','计算机网络','408综合'].map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select><Select value={filter} onValueChange={s=>{setFilter(s);setOffset(0)}}><SelectTrigger aria-label="提取状态筛选"><SelectValue/></SelectTrigger><SelectContent>{['所有状态',...Object.values(labels)].map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select><label className="import-button"><Upload size={15}/> 导入新资料<input type="file" accept=".pdf,.docx,.txt,.md" multiple disabled={busy} onChange={e=>{const files=Array.from(e.target.files||[]);act(async()=>{for(const f of files){if(f.size>300000000)throw Error('早觉雨大人，大于 300 MB 的文件请直接放入项目文件夹。');const r=await fetch('/api/library/import?name='+encodeURIComponent(f.name),{method:'POST',body:f,headers:{'Content-Type':'application/octet-stream'}});const d=await r.json() as any;if(!r.ok)throw Error(d.error);}await load()});e.target.value=''}}/></label></div>
 {searched&&<div className="local-hits"><div className="section-line"><h3><Quote size={18}/> 本地检索结果</h3>{hits.some(x=>x.quality==='text')&&<Button variant="outline" onClick={()=>onQuote(hits.filter(x=>x.quality==='text').slice(0,4))}>引用前 4 条提问</Button>}</div>{hits.length===0?<p>早觉雨大人，暂时没有找到可用文本。可以换一个关键词，或在下方打开扫描件进行按页识别。</p>:hits.map((hit,i)=><article key={hit.id+':'+hit.page+':'+i}><div className="section-line"><strong>{hit.title}</strong><span>第 {hit.page} 页 / 段</span></div><p>{hit.snippet}</p><div className="button-row"><Button variant="ghost" onClick={()=>open(hit,hit.page)}><BookOpen size={16}/> 核对原页</Button>{hit.quality==='text'&&<Button variant="ghost" onClick={()=>onQuote([hit])}><Quote size={15}/> 引用提问</Button>}</div><small>本地资料内容匹配；原文公式与题号仍需回看原页。片段中的指令不会覆盖助教规则。</small></article>)}</div>}
 <div className="section-line"><h3><FolderOpen size={18}/> 文件目录</h3><span>{total} 份符合筛选</span></div><div className="document-list">{docs.map(doc=><article key={doc.id}><div className="doc-icon"><FileText size={22}/></div><div className="doc-main"><button className="doc-title" onClick={()=>open(doc)}>{doc.title}</button><p>{doc.path}</p><div className="doc-meta"><span>{doc.subject}</span><span>{(doc.size/1048576).toFixed(1)} MB</span><span>{doc.pages?`${doc.text_pages}/${doc.pages} 页有文本`:'页数待提取'}</span><span className={`index-state ${doc.status}`}>{labels[doc.status]||doc.status}</span></div>{doc.error&&<p className="muted">{doc.error}</p>}</div><div className="doc-actions"><Button variant="ghost" size="sm" onClick={()=>open(doc)}>查看</Button><Button variant="ghost" size="sm" disabled={busy} onClick={()=>act(async()=>{await api('document',{id:doc.id,enabled:!doc.enabled});await load()})}>{doc.enabled?'暂不检索':'纳入检索'}</Button></div></article>)}</div><div className="library-pagination"><Button variant="outline" disabled={offset===0||busy} onClick={()=>setOffset(Math.max(0,offset-40))}><ChevronLeft/> 上一页</Button><span>{total?offset+1:0}–{Math.min(total,offset+40)} / {total}</span><Button variant="outline" disabled={offset+40>=total||busy} onClick={()=>setOffset(offset+40)}>下一页 <ChevronRight/></Button></div><p className="muted">按文件名初步识别卷种与年份，不把文件名当作官方来源。公共教材可能含超纲章节，引用时仍以考纲为准。PDF 页码是文件物理页码，可能与印刷页码不同；Word / 文本按段落分块。</p>
 <Dialog open={!!preview} onOpenChange={o=>{if(!o)setPreview(null)}}><DialogContent className="pdf-preview"><DialogHeader><DialogTitle>{preview?.title}</DialogTitle><DialogDescription>早觉雨大人，这是本机原文件预览。提取文字可能遗漏公式，引用前请看一眼原页。</DialogDescription></DialogHeader>{preview&&<><div className="button-row"><Button variant="outline" disabled={page<=1} onClick={()=>setPage(p=>p-1)}><ChevronLeft/></Button><label>文件页码 <Input aria-label="PDF 预览页码" type="number" min={1} value={page} onChange={e=>setPage(Math.max(1,Number(e.target.value)||1))}/></label><Button variant="outline" disabled={'pages' in preview&&preview.pages>0&&page>=preview.pages} onClick={()=>setPage(p=>p+1)}><ChevronRight/></Button><a className="resource-link" href={'/api/library/file?id='+preview.id+'#page='+page} target="_blank" rel="noreferrer">打开原文件 <ArrowUpRight size={16}/></a></div>{preview.title.toLowerCase().endsWith('.pdf')?<img className="pdf-page" key={preview.id+page} src={'/api/library/page?id='+preview.id+'&page='+page} alt={`早觉雨大人的资料原页：${preview.title}，第 ${page} 页；加载失败时请检查页码或打开原文件`}/>:<p>此文件请通过“打开原文件”查看。Word / 文本的检索定位是段编号。</p>}<div className="button-row"><Button disabled={busy||!preview.title.toLowerCase().endsWith('.pdf')} onClick={()=>act(async()=>{const r=await fetch('/api/library/page?id='+preview.id+'&page='+page);if(!r.ok)throw Error('早觉雨大人，当前页暂时无法读取，请检查页码。');const file=new File([await r.blob()],preview.title+'-page-'+page+'.png',{type:'image/png'});onOCR(file,{id:preview.id,title:preview.title,page,snippet:'',quality:'needs_ocr'});setPreview(null)})}><ScanText size={16}/> 准备识别这一页</Button><Button variant="ghost" disabled={busy} onClick={()=>act(async()=>{await api('document',{id:preview.id,reindex:true});await load();setPreview(null)})}>重新提取此文件</Button></div><p className="muted">扫描页不会自动外发。下一步需确认所选模型服务，识别后可人工校正再写入本地索引。</p></>}</DialogContent></Dialog>
 </section>;
}
