"use client";
import {useState} from 'react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Input} from '@/components/ui/input';
import {Button} from '@/components/ui/button';
import {providers,type ModelConfig} from '@/lib/providers';
export default function ModelSettings({open,onOpenChange,config,onConfig,apiKey,onKey}:{open:boolean;onOpenChange:(v:boolean)=>void;config:ModelConfig;onConfig:(v:ModelConfig)=>void;apiKey:string;onKey:(v:string)=>void}){
const [status,setStatus]=useState(''),[models,setModels]=useState<string[]>([]),[busy,setBusy]=useState(false);
async function list(){setBusy(true);setStatus('');try{const r=await fetch('/api/models',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({key:apiKey,config})});const d=await r.json() as any;if(!r.ok)throw Error(d.error);setModels(d.models);setStatus(`早觉雨大人，服务返回了 ${d.models.length} 个模型。可选择一个，图片能力仍需查看服务商说明。`);}catch(e){setStatus((e as Error).message)}finally{setBusy(false)}}
return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>早觉雨大人的模型设置</DialogTitle><DialogDescription>支持多个服务商。密钥只保留当前页面内存，刷新清除；切换服务会清空密钥，避免误发。</DialogDescription></DialogHeader><label>模型服务</label><Select value={config.provider} onValueChange={id=>{const p=providers.find(x=>x.id===id)!;onConfig({provider:p.id,baseUrl:p.baseUrl,textModel:p.textModel,visionModel:p.visionModel});onKey('');setModels([]);setStatus('')}}><SelectTrigger aria-label="选择模型服务"><SelectValue/></SelectTrigger><SelectContent>{providers.map(p=><SelectItem key={p.id} value={p.id}>{p.name}</SelectItem>)}</SelectContent></Select><label htmlFor="base-url">API 基础地址（不含 /chat/completions）</label><Input id="base-url" value={config.baseUrl} onChange={e=>{onConfig({...config,baseUrl:e.target.value.trim()});onKey('')}} placeholder="https://服务商域名/v1"/>{config.provider==='qwen'&&<div className="button-row"><Button variant="outline" size="sm" onClick={()=>{onConfig({...config,baseUrl:'https://dashscope.aliyuncs.com/compatible-mode/v1'});onKey('')}}>北京</Button><Button variant="outline" size="sm" onClick={()=>{onConfig({...config,baseUrl:'https://dashscope-intl.aliyuncs.com/compatible-mode/v1'});onKey('')}}>新加坡</Button></div>}<label htmlFor="api-key">此服务的 API Key</label><Input id="api-key" type="password" autoComplete="off" value={apiKey} onChange={e=>onKey(e.target.value.trim())} placeholder="填写所选服务的密钥"/><div className="model-fields"><div><label htmlFor="text-model">文本模型 ID</label><Input id="text-model" value={config.textModel} onChange={e=>onConfig({...config,textModel:e.target.value})}/></div><div><label htmlFor="vision-model">图片模型 ID（可留空）</label><Input id="vision-model" value={config.visionModel} onChange={e=>onConfig({...config,visionModel:e.target.value})} placeholder="支持图片输入的模型"/></div></div><Button variant="outline" disabled={busy||!apiKey} onClick={list}>{busy?'正在检查…':'读取账号可用模型'}</Button>{status&&<p role="status">{status}</p>}{models.length>0&&<Select onValueChange={v=>onConfig({...config,textModel:v})}><SelectTrigger aria-label="选择账号返回的文本模型"><SelectValue placeholder="选为文本模型"/></SelectTrigger><SelectContent>{models.map(m=><SelectItem key={m} value={m}>{m}</SelectItem>)}</SelectContent></Select>}<p className="muted">自定义地址需在服务端 MODEL_ALLOWED_HOSTS 配置准确域名。仅用 HTTPS，禁止转跳与内网地址。联网搜索目前支持千问；其他服务可使用本地检索片段。价格和模型可用性以服务商为准。</p><a className="resource-link" href={providers.find(p=>p.id===config.provider)?.docs} target="_blank" rel="noreferrer">所选服务官方说明</a><div className="button-row"><Button onClick={()=>onOpenChange(false)}>完成设置</Button><Button variant="outline" onClick={()=>{onKey('');setStatus('早觉雨大人，页面中的密钥已清除。')}}>清除密钥</Button></div></DialogContent></Dialog>;
}
