import {owner,db,env,secret,failure,HttpError,json} from '@/lib/server';
import {seal,unseal,base64,fromBase64} from '@/lib/crypto';
import {createEmptyCard,fsrs,Rating,type Card,type Grade} from 'ts-fsrs';
import {topics} from '@/lib/curriculum';
const scheduler=fsrs({enable_fuzz:false});
async function decode(row:Record<string,unknown>,user:string){const data=await unseal(fromBase64(row.payload as string),secret(),`${user}:${row.id}`);return {...row,owner:undefined,object_key:undefined,payload:JSON.parse(new TextDecoder().decode(data)),hasImage:!!row.object_key};}
async function encode(payload:unknown,user:string,id:string){return base64(await seal(new TextEncoder().encode(JSON.stringify(payload)),secret(),`${user}:${id}`));}
export async function GET(request:Request){try{const user=await owner(request);const {results}=await db().prepare('SELECT * FROM records WHERE owner=? ORDER BY created DESC LIMIT 300').bind(user).all();return Response.json({records:await Promise.all(results.map(row=>decode(row,user)))},{headers:{'Cache-Control':'no-store'}});}catch(e){return failure(e);}}
export async function POST(request:Request){try{const user=await owner(request);const body=await json(request);if(!topics.some(t=>t.id===body.topic)||!['review','mistake','progress'].includes(body.kind)||typeof body.text!=='string'||body.text.length>20000)throw new HttpError('早觉雨大人，请补全记录内容。');const id=crypto.randomUUID(),now=Date.now();const payload={text:body.text,answer:String(body.answer||'').slice(0,10000),cause:String(body.cause||'待复核'),card:createEmptyCard(new Date(now))};await db().prepare('INSERT INTO records(id,owner,kind,topic,payload,created,due) VALUES(?,?,?,?,?,?,?)').bind(id,user,body.kind,body.topic,await encode(payload,user,id),now,now).run();return Response.json({id});}catch(e){return failure(e);}}
export async function PATCH(request:Request){try{const user=await owner(request),body=await json(request);if(![1,2,3,4].includes(body.rating))throw new HttpError('请选择复习感受');const row=await db().prepare('SELECT * FROM records WHERE id=? AND owner=?').bind(body.id,user).first();if(!row)throw new HttpError('记录不存在',404);if(Number(body.version)!==Number(row.version))throw new HttpError('记录已更新，请刷新后再试',409);const record=await decode(row,user);const payload=record.payload;const card=payload.card as Card;card.due=new Date(card.due);if(card.last_review)card.last_review=new Date(card.last_review);payload.card=scheduler.next(card,new Date(),body.rating as Grade).card;const result=await db().prepare('UPDATE records SET payload=?,due=?,version=version+1 WHERE id=? AND owner=? AND version=?').bind(await encode(payload,user,body.id),payload.card.due.getTime(),body.id,user,body.version).run();if(result.meta.changes!==1)throw new HttpError('记录已更新，请刷新后再试',409);return Response.json({ok:true,due:payload.card.due});}catch(e){return failure(e);}}
export async function DELETE(request:Request){try{const user=await owner(request),body=await json(request);const row=await db().prepare('SELECT object_key FROM records WHERE id=? AND owner=?').bind(body.id,user).first();if(!row)throw new HttpError('记录不存在',404);if(row.object_key){if(!env.BUCKET)throw new HttpError('图片存储暂时不可用',503);await env.BUCKET.delete(String(row.object_key));}await db().prepare('DELETE FROM records WHERE id=? AND owner=?').bind(body.id,user).run();return Response.json({ok:true});}catch(e){return failure(e);}}

