import './sites-env.mjs';
import {existsSync,mkdirSync,writeFileSync} from 'node:fs';
import {randomBytes} from 'node:crypto';
import {spawnSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
process.chdir(fileURLToPath(new URL('..',import.meta.url)));
mkdirSync('.sites-runtime',{recursive:true});
if(!existsSync('.env'))writeFileSync('.env',`STORAGE_KEY=${randomBytes(32).toString('hex')}\n`,{flag:'wx'});
const config={name:'gentle-tutor-local',compatibility_date:'2026-09-24',d1_databases:[{binding:'DB',database_name:'site-creator-d1',database_id:'00000000-0000-4000-8000-000000000000',migrations_dir:'../drizzle'}]};
writeFileSync('.sites-runtime/local-wrangler.json',JSON.stringify(config));
const r=spawnSync(process.execPath,['node_modules/wrangler/bin/wrangler.js','d1','migrations','apply','DB','--local','--config','.sites-runtime/local-wrangler.json','--persist-to','.wrangler/state'],{stdio:'inherit',env:{...process.env,WRANGLER_SEND_METRICS:'false'}});
if(r.error)throw r.error;process.exitCode=r.status||0;
